### ISSUE TITLE
Re-register failed DOIs

### ISSUE THREAD

**Issue by everreau** [eScholarship/janeway_ezid_plugin#21]
Information from EZID team:
doi
- [x] 10.5070/p540263635
- [x] 10.5070/p540263637
- [ ] 10.5070/r53061218
- [ ] 10.5070/r53061219
- [ ] 10.5070/r53061220
- [ ] 10.5070/r53061221
- [x] 10.5070/w4jwa.189
- [ ] 10.5811/cpcem.1245
- [x] 10.5811/westjem.58717

**Comment by everreau** [comment]
It looks like there is still something wrong with the corporate author schema

Corporate author issues:
10.5070/p540263635
10.5070/p540263637
-  
 - Attribute 'sequence' must appear on element 'ns0:organization'. Error: cvc-complex-type.4: Attribute 'contributor_role' must appear on element 'ns0:organization'.

**Comment by everreau** [comment]
These dois are from a journal called "react/review" that is not in janeway yet.  I'm not sure where they were registered from.

The crossref error in ezid just says "registration in progress".  Don't know what that means maybe they should just be retried.

10.5070/r53061218
10.5070/r53061219
10.5070/r53061220
10.5070/r53061221

**Comment by everreau** [comment]
Successfully republished:

10.5070/w4jwa.189
10.5811/westjem.58717

**Comment by Charlie-Rock** [comment]
> I'm confused what's going on with this guy:
> 
> https://journalpub.escholarship.org/uciem_cpcem/manage/archive/article/1245/ https://escholarship.org/uc/item/1vm9v60z
> 
> in escholarship it was published in the "Articles in Press" but it's not in that issue anymore, maybe it's in 7/3 but I don't see it showing up there either.

I reassigned the DOI and re-published it in 7/3 and it's resolving!

**Comment by Charlie-Rock** [comment]
> These dois are from a journal called "react/review" that is not in janeway yet. I'm not sure where they were registered from.
> 
> The crossref error in ezid just says "registration in progress". Don't know what that means maybe they should just be retried.
> 
> 10.5070/r53061218 10.5070/r53061219 10.5070/r53061220 10.5070/r53061221

Republished and the DOIs now resolve!

**Comment by Charlie-Rock** [comment]
> It looks like there is still something wrong with the corporate author schema
> 
> 10.5070/p540263635 10.5070/p540263637
> 
> Attribute 'sequence' must appear on element 'ns0:organization'. Error: cvc-complex-type.4: Attribute 'contributor_role' must appear on element 'ns0:organization'.

Both DOIs are now resolving, I just deleted the (corporate) authors and added them again, then republished.
